name: Rust

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Install Rust components
      run: rustup component add rustfmt && rustup component add clippy
    - uses: actions/cache@v2
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target
        key: ${{ runner.os }}-cargo-${{ hashFiles('Cargo.lock') }}
    - name: Install capsule
      run: cargo install ckb-capsule --version 0.9.0 --locked
    - name: Check Rust format
      run: cargo fmt -- --check
    - name: Cargo clippy check
      env:
        RUSTFLAGS: -D warnings
      run: cargo clippy
    - name: Tests
      run: make
